version: '3.8'

services:
  api:
    image: solomonbroadbent/password.solthe.dev:api-latest
    container_name: api.password.solthe.dev
    build:
      context: .
    expose:
      - '50051'
    networks:
      - password.solthe.dev

  reverse-proxy:
    image: solomonbroadbent/password.solthe.dev:reverse-proxy-latest
    container_name: reverse-proxy.password.solthe.dev
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    build:
      context: reverse-proxy
    ports:
      - '80:80'
    networks:
      - password.solthe.dev

networks:
  password.solthe.dev:
