parameters: {}
environment: {}
packages:
  - name: password.solthe.dev
    environment: {}
    parameters: {}
    actions:
      - name: test
        main: ''
        runtime: 'go:1.20'
        environment: {}
        parameters: {}
            # milliseconds
            # timeout: 5000
            # megabytes
            # memory: 150
            # kilobytes
            # logs: 100000
          
